### ISSUE TITLE
Trying to run on Windows

### ISSUE THREAD

**Issue by mlcrow** [Blokkendoos/AACircuit#1]
I'm attempting to run on windows. I believe I have all the dependencies installed but when I try running
`python AACircuit.py`
I get the following:
`Traceback (most recent call last):
  File "C:\Users\mitch\Documents\GitHub\AACircuit\AACircuit.py", line 11, in <module>
    from application.controller import Controller
  File "C:\Users\mitch\Documents\GitHub\AACircuit\application\controller.py", line 13, in <module>
    from locale import gettext as _
ImportError: cannot import name 'gettext' from 'locale' (C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.9_3.9.1520.0_x64__qbz5n2kfra8p0\lib\locale.py)`

**Comment by Blokkendoos** [comment]
No Windows machine here to verify, please try the code in the latest commit.

**Comment by Blokkendoos** [comment]
Hi,

Did you give the latest commit a try? And with what result?
Regards,
J

**Comment by mlcrow** [comment]
Sorry for the delay in in response. Unfortunately, there is no change with the newest commit. I've been doing some more investigation and my understanding is I cannot run PyGObject except through MSYS2, which I've be able to get their example from https://pygobject.readthedocs.io/en/latest/getting_started.html#windows-logo-windows running, but I'm not sure I can install the other necessary python dependencies through that.

I've got a linux machine available to me so I'll try running on that and I'm sure it'll go much more smoothly.

**Comment by Blokkendoos** [comment]
> Facing the same issue on macOS 10.14.6 (18G8022)

Could you give some more information? Is it the same error message as microw had on Windows?
What result gives import in a Python shell, e.g.:
```
$ python --version
$ python
>>> import locale
>>> print(locale.getdefaultlocale())
('nl_NL', 'UTF-8')  <= example language and encoding returned
('en_GB', 'UTF-8')
>>> from locale import gettext
>>> print(gettext("Test msg"))
Test msg
```

**Comment by julian-weinert** [comment]
Sure, here is the requested information:

```python
Python 3.9.1 (default, Jan  8 2021, 17:15:36)
[Clang 11.0.0 (clang-1100.0.33.17)] on darwin
Type "help", "copyright", "credits" or "license" for more information.
>>> import locale
>>> print(locale.getdefaultlocale())
('en_GB', 'UTF-8')
>>> from locale import gettext
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
ImportError: cannot import name 'gettext' from 'locale'
```

**Comment by Blokkendoos** [comment]
Could you please try again with the latest commit?

**Comment by Blokkendoos** [comment]
Support windows with msys2 (python 3.9.13) added
