### ISSUE TITLE
Can't get it to run on Windows 10

### ISSUE THREAD

**Issue by junkjunker** [Blokkendoos/AACircuit#4]
I'm eager to try this, but after installing the latest Python (3.11) and trying to run it, I get the following error. Am I doing something wrong?

`C:\PortableApps\AACircuit-master>python aacircuit.py
Traceback (most recent call last):
  File "C:\PortableApps\AACircuit-master\aacircuit.py", line 11, in <module>
    from application.controller import Controller
  File "C:\PortableApps\AACircuit-master\application\controller.py", line 9, in <module>
    import xerox
ModuleNotFoundError: No module named 'xerox'`

Thanks!

**Comment by Blokkendoos** [comment]
xerox is one of the dependencies, listed in the README.
Note that this repo does not provide a source distribution, so you need to install dependencies yourself (e.g. in a virtual environment) "pip install xerox, pypubsub, bresenham" I don't know about Gtk+3 installation in a Windows environment.

**Comment by junkjunker** [comment]
Ok, thanks.  Sounds like more trouble that it is worth when the original project still runs on Windows 10.
