### ISSUE TITLE
dependencies to make aacircuitpy run on Linux

### ISSUE THREAD

**Issue by nnako** [Blokkendoos/AACircuit#5]
Hi,

I'd love to try AACircuitPy on Linux. I learned that installing and running it on Windows seems to be too difficult (at least for a "normal" person without extensive system knowledge). But on Linux, I thought, this would be easier...

This is what I've tried so far:

```bash
# prepare the virtual environment
cd ~
python3 -m venv ENV__aacircuit__py37
source ENV__aacircuit__py37/bin/activate

# install dependencies
pip install xerox      # v0.4.1 gets installed
pip install pypubsub   # v4.0.3 gets installed
pip install bresenham  # v0.2.1 gets installed

# get the sources
git clone https://github.com/Blokkendoos/AACircuit.git APP__aacircuit

# walk into project folder and try it
cd APP__aacircuit
python aacircuit.py
```

unfortunately, this seems to lead to a missing module "gi", so ...

```bash
# install further dependency
pip install gi   # results in installation of
                 # certifi v2022.12.7
                 # charset-normalizer v2.1.1
                 # gi v1.2
                 # idna v3.4
                 # requests v2.28.1
                 # urllib3 v1.26.13

# try to execute
python aacircuit.py
```

now, the newly installed `gi` package shows an error which stems from a Python v2 statement `print url` (missing parentheses). Before I try to re-work the `gi` source code, I'd rather like to ask a question, here ;-) .

could someone drop some lines of bash commands in order for others to be successful? I tried on a RaspberryPi, using Python v3.7 . Can anybody help me?

**Comment by Blokkendoos** [comment]
Try:
`pip install pycairo`
`pip install PyGobject`
Thread: https://stackoverflow.com/questions/44213921/python-3-installing-gi-package-with-pip

**Comment by nnako** [comment]
Hi @Blokkendoos ,

thanks for your reply.

In the end, I had to use this sequence in order to install and run `aacircuitpy` on a RaspberryPi:

```bash
# install system dependencies
sudo apt update
sudo apt install libgirepository1.0-dev gcc libcairo2-dev pkg-config
sudo apt install python3-dev gir1.2-gtk-3.0

# prepare the Python virtual environment
cd ~
python3 -m venv ENV__aacircuit__py37
source ENV__aacircuit__py37/bin/activate

# install Python dependencies
pip install xerox
pip install pypubsub
pip install bresenham
pip install pycairo
pip install PyGObject

# get and start the application
git clone https://github.com/Blokkendoos/AACircuit.git APP__aacircuit
cd APP__aacircuit
python aacircuit.py
```
