### ISSUE TITLE
structural information about aacircuitpy

### ISSUE THREAD

**Issue by nnako** [Blokkendoos/AACircuit#7]
Hi,

I would be interested in the structure of `aacircuitpy`. Are there any structural diagrams, concept maps, ... which could be read in order to quicker understand the application structure?

- overview about what is done in which code module
- connections between code modules
- usage of external functionalities
- ...

of course, a real software developer would read the code modules and build something like this within his head, but maybe there are some structure sketches you could provide?

**Comment by Blokkendoos** [comment]
There is no design documentation.

The code is based on a simple MVC framework, implemented by `application/controller.py` and `application/main_window.py`. Information exchange between GUI and logic is done with (pubsub) messaging.
The class hierarchy can be generated with [doxygen](https://www.doxygen.nl/) for which a Doxyfile is present in the project.

What helps in analyzing code is to open all source files in an IDE that supports code navigation. That allows you to easily jump between method usage and definitions. For this you could use a small and lightweight IDE such as [Geany](https://www.geany.org/).
