### ISSUE TITLE
Using the components in Asciio

### ISSUE THREAD

**Issue by nkh** [Blokkendoos/AACircuit#8]
First of all ... FUN!

It's great to see people keeping ASCII art living in applications that are also practical; κῦδος!

I'm the authorof https://github.com/nkh/P5-App-Asciio, there was a a stencil with a library of electronic components to use, https://github.com/fbagagli/asciio_contrib/blob/master/stencils/circuit, but it didn't go very far;  would it be OK if I use yours?

**Comment by Blokkendoos** [comment]
> First of all ... FUN!
> It's great to see people keeping ASCII art living in applications that are also practical; κῦδος!
> I'm the authorof https://github.com/nkh/P5-App-Asciio, there was a a stencil with a library of electronic components to use, https://github.com/fbagagli/asciio_contrib/blob/master/stencils/circuit, but it didn't go very far; would it be OK if I use yours?
Note that the original was published by [Andy](https://github.com/Andy1978/AACircuit)
Since it is GPL, just use it and refer to me and Andy's repo.
Success with AsciIO.
